Assignment3.Web/Controllers/CotacaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment3.Web.Models;

namespace Assignment3.Web.Controllers
{
    public class CotacaoController : ControllerBase
    {
        private ModeloDados db = new ModeloDados();

        // GET: Cotacao
        public ActionResult Index()
        {
            try
            {
                ValidateSessionActive();

                var cotacao = db.Cotacao.Include(c => c.Cliente).Include(c => c.Solicitante);
                if (cotacao != null && cotacao.Count() > 0)
                    return View(cotacao.Where(x => x.ClienteId == this.ClienteLogado.ClienteId).ToList());

                return View(cotacao);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            
        }

        // GET: Cotacao/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                ValidateSessionActive();

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Cotacao cotacao = db.Cotacao.Include(c => c.Cliente).Include(c => c.Solicitante).Where(x => x.CotacaoId == id).FirstOrDefault();
                if (cotacao == null)
                {
                    return HttpNotFound();
                }

                switch (cotacao.TipoCotacao)
                {
                    case TipoCotacao.CotacaoAutomovel:
                        cotacao.ItensAutomovel = db.CotacaoItemAutomovels.Where(x => x.CotacaoId == cotacao.CotacaoId).ToList();
                        break;
                    case TipoCotacao.CotacaoImovel:
                        cotacao.ItensImovel = db.CotacaoItemImovels.Where(x => x.CotacaoId == cotacao.CotacaoId).ToList();
                        break;                    
                }

                return View(cotacao);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            
        }

        // GET: Cotacao/Create
        public ActionResult Create()
        {
            try
            {
                ValidateSessionActive();

                Cotacao cotacao = new Cotacao();
                cotacao.ClienteId = this.ClienteLogado.ClienteId;
                cotacao.DataSolicitacao = DateTime.Now;
                cotacao.DataValidade = DateTime.Now.AddDays(10);

                var solicitantes = db.Solicitantes.Where(x => x.ClienteId == this.ClienteLogado.ClienteId).ToList();
                if (solicitantes != null && solicitantes.Count() > 0)
                    ViewBag.Solicitantes = solicitantes;
                else
                    ViewBag.MensagemValidacao = "É necessário realizar o cadastro do cliente antes de criar a cotação.";

                return View(cotacao);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            
        }

        // POST: Cotacao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cotacao cotacao)
        {
            if (ModelState.IsValid)
            {
                cotacao.ClienteId = this.ClienteLogado.ClienteId;
                cotacao.DataSolicitacao = DateTime.Now;
                cotacao.DataValidade = DateTime.Now.AddDays(10);

                db.Cotacao.Add(cotacao);
                db.SaveChanges();

                switch (cotacao.TipoCotacao)
                {
                    case TipoCotacao.CotacaoAutomovel:
                        return RedirectToAction("Create", "CotacaoItemAutomovel", new { id = cotacao.CotacaoId });
                    case TipoCotacao.CotacaoImovel:
                        return RedirectToAction("Create", "CotacaoItemImovel", new { id = cotacao.CotacaoId });
                }

                
            }

            ViewBag.ClienteId = new SelectList(db.Cliente, "ClienteId", "Nome", cotacao.ClienteId);
            ViewBag.SolicitanteId = new SelectList(db.Solicitantes, "SolicitanteId", "Nome", cotacao.SolicitanteId);
            return View(cotacao);
        }

        // GET: Cotacao/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                ValidateSessionActive();

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Cotacao cotacao = db.Cotacao.Find(id);
                if (cotacao == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ClienteId = new SelectList(db.Cliente, "ClienteId", "Nome", cotacao.ClienteId);
                ViewBag.SolicitanteId = new SelectList(db.Solicitantes, "SolicitanteId", "Nome", cotacao.SolicitanteId);
                return View(cotacao);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            
        }

        // POST: Cotacao/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cotacao cotacao)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cotacao).State = EntityState.Modified;
                db.SaveChanges();

                switch (cotacao.TipoCotacao)
                {
                    case TipoCotacao.CotacaoAutomovel:
                        return RedirectToAction("Create", "CotacaoItemAutomovel", new { id = cotacao.CotacaoId });                        
                    case TipoCotacao.CotacaoImovel:
                        return RedirectToAction("Create", "CotacaoItemImovel", new { id = cotacao.CotacaoId });                    
                }                                
            }
                        
            return View(cotacao);
        }

        // GET: Cotacao/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                ValidateSessionActive();

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Cotacao cotacao = db.Cotacao.Find(id);
                if (cotacao == null)
                {
                    return HttpNotFound();
                }
                return View(cotacao);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            
        }

        // POST: Cotacao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cotacao cotacao = db.Cotacao.Find(id);
            db.Cotacao.Remove(cotacao);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ConsultaCotacao(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    ViewBag.MensagemStatus = "Desculpe mas não encontramos nenhum dado para esta cotação. Verifique com seu corretor se o link informado está correto.";
                    return View();
                }
                                
                var solicitante = db.Solicitantes.Where(x => x.ChaveIdentificacao == id).FirstOrDefault();
                if (solicitante == null)
                {
                    ViewBag.MensagemStatus = "Desculpe mas não encontramos nenhum dado para esta cotação. Verifique com seu corretor se o link informado está correto.";
                    return View();
                }

                Cotacao cotacao = db.Cotacao.Include(c => c.Cliente).Include(c => c.Solicitante).Where(x => x.SolicitanteId == solicitante.SolicitanteId).FirstOrDefault();
                if (cotacao == null)
                {
                    ViewBag.MensagemStatus = "Desculpe mas não encontramos nenhum dado para esta cotação. Verifique com seu corretor se o link informado está correto.";
                    return View();
                }

                switch (cotacao.TipoCotacao)
                {
                    case TipoCotacao.CotacaoAutomovel:
                        cotacao.ItensAutomovel = db.CotacaoItemAutomovels.Where(x => x.CotacaoId == cotacao.CotacaoId).ToList();
                        break;
                    case TipoCotacao.CotacaoImovel:
                        cotacao.ItensImovel = db.CotacaoItemImovels.Where(x => x.CotacaoId == cotacao.CotacaoId).ToList();
                        break;                    
                }

Assignment3.Web/Controllers/SolicitanteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment3.Web.Models;

namespace Assignment3.Web.Controllers
{
    public class SolicitanteController : ControllerBase
    {
        private ModeloDados db = new ModeloDados();

        // GET: Solicitante
        public ActionResult Index()
        {
            try
            {
                ValidateSessionActive();

                var solicitantes = db.Solicitantes.Include(s => s.Cliente);
                if (solicitantes != null && solicitantes.Count() > 0)
                    return View(solicitantes.Where(x => x.ClienteId == this.ClienteLogado.ClienteId).ToList());

                return View(solicitantes);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }            
        }

        // GET: Solicitante/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                ValidateSessionActive();

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Solicitante solicitante = db.Solicitantes.Find(id);
                if (solicitante == null)
                {
                    return HttpNotFound();
                }
                return View(solicitante);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            
        }

        // GET: Solicitante/Create
        public ActionResult Create()
        {
            ViewBag.ClienteId = new SelectList(db.Cliente, "ClienteId", "Nome");
            return View();
        }

        // POST: Solicitante/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Solicitante solicitante)
        {
            if (ModelState.IsValid)
            {
                solicitante.ClienteId = this.ClienteLogado.ClienteId;
                db.Solicitantes.Add(solicitante);
                db.SaveChanges();

                solicitante.ChaveIdentificacao = string.Format("{0}{1}",
                    DateTime.Now.ToString("yyyyMMdd_hhMMss"),
                    solicitante.SolicitanteId);
                db.Entry(solicitante).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.ClienteId = new SelectList(db.Cliente, "ClienteId", "Nome", solicitante.ClienteId);
            return View(solicitante);
        }

        // GET: Solicitante/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                ValidateSessionActive();

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Solicitante solicitante = db.Solicitantes.Find(id);
                if (solicitante == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ClienteId = new SelectList(db.Cliente, "ClienteId", "Nome", solicitante.ClienteId);
                return View(solicitante);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            
        }

        // POST: Solicitante/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Solicitante solicitante)
        {
            if (ModelState.IsValid)
            {
                solicitante.ClienteId = this.ClienteLogado.ClienteId;
                db.Entry(solicitante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClienteId = new SelectList(db.Cliente, "ClienteId", "Nome", solicitante.ClienteId);
            return View(solicitante);
        }

        // GET: Solicitante/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                ValidateSessionActive();

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Solicitante solicitante = db.Solicitantes.Find(id);
                if (solicitante == null)
                {
                    return HttpNotFound();
                }
                return View(solicitante);
            }
            catch (System.Security.Authentication.AuthenticationException)
            {
                return RedirectToAction("Login", "Cliente");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            
        }

        // POST: Solicitante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Solicitante solicitante = db.Solicitantes.Find(id);
            db.Solicitantes.Remove(solicitante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment3.Web/Views/Cliente/Create.cshtml
@model Assignment3.Web.Models.Cliente

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutHeaderSlim.cshtml";
}

<div class="container">


    <div class="alert alert-info" role="alert">
        <span> Nossa pré campanha já foi finalizada. Caso tenha interesse, entre em contato conosco através do e-mail contato@seguracliente.com.br </span>
    </div>



    @*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Cadastro de Cliente</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CpfCnpj, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CpfCnpj, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CpfCnpj, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Cadastrar" class="btn btn-primary btn-lg" />
                </div>
            </div>
        </div>
    }*@

    <div>
        <a href="http://seguracliente.com.br/">Voltar para a página inicial</a>
    </div>

</div>

Assignment3.Web/Views/Cliente/Delete.cshtml
@model Assignment3.Web.Models.Cliente

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutHeaderSlim.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CpfCnpj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CpfCnpj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Assignment3.Web/Views/Cliente/Details.cshtml
@model Assignment3.Web.Models.Cliente

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutHeaderSlim.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CpfCnpj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CpfCnpj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClienteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Assignment3.Web/Views/Cliente/Edit.cshtml
@model Assignment3.Web.Models.Cliente

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutHeaderSlim.cshtml";
}

<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Editar dados Cliente</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ClienteId)

            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CpfCnpj, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CpfCnpj, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CpfCnpj, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salvar alterações" class="btn btn-primary btn-lg" />
                </div>
            </div>
        </div>
    }
        
    <p>
        <a href="@Url.Action("Index", "Home")">Voltar para cadastro</a>
    </p>

</div>

Assignment3.Web/Views/Cliente/HomePortal.cshtml
@model Assignment3.Web.Models.Cliente

@{
    ViewBag.Title = "HomePortal";
    Layout = "~/Views/Shared/_LayoutHeaderPortal.cshtml";
}

<div class="container">
    <h2>Portal do Corretor</h2>
    <br />

    <div class="row">
        <div class="col-md-3">
            <a href="@Url.Action("Create", "Solicitante")" class="btn btn-default btn-raised btn-lg">
                CADASTRAR NOVO CLIENTE
            </a>
        </div>  
        <div class="col-md-3">
            <a href="@Url.Action("Create", "Cotacao")" class="btn btn-default btn-raised btn-lg">
                CADASTRAR NOVA COTAÇÃO
            </a>
        </div>                

    </div>
    
    

    <br /><br />

    @if (Model.Cotacoes != null && Model.Cotacoes.Count > 0)
    {

        @Html.ActionLink("Visualizar todas as cotações", "Index", "Cotacao")

        <br /><br />

        <fieldset>
            <legend>Cotações em aberto</legend>
            <div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Nome do Cliente</th>
                            <th>Data da Solicitação</th>
                            <th>Data de Validade</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Cotacoes)
                        {
                            <tr>
                                <td> @string.Format("{0} {1}", item.Solicitante.Nome, item.Solicitante.Sobrenome) </td>
                                <td> @item.DataSolicitacao.ToString("dd/MM/yyyy") </td>
                                <td> @item.DataValidade.ToString("dd/MM/yyyy") </td>  
                                <td> <a href="@Url.Action("Details", "Cotacao",new { id= item.CotacaoId })">Detalhes</a> </td>                              
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </fieldset>
    }
    else
    {
        <div class="alert alert-info" role="alert">
            <span>Não há cotações em aberto</span>
        </div>
    }


</div>

Assignment3.Web/Views/Cliente/Index.cshtml
@model IEnumerable<Assignment3.Web.Models.Cliente>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutHeaderSlim.cshtml";
}

<div class="container">

    <h2>Clientes</h2>

    <p>

    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CpfCnpj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sobrenome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CpfCnpj)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefone)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.ClienteId }) |*@
                    @*@Html.ActionLink("Details", "Details", new { id = item.ClienteId }) |*@
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.ClienteId })*@
                </td>
            </tr>
        }

    </table>


</div>